package pt.bucho.weather.state;

public enum WeatherState {
	
	CEU_LIMPO,
	CEU_POUCO_NUBLADO,
	PERIODOS_CEU_MT_NUBLADO,
	AGUACEIROS_FRACOS,
	AGUACEIROS,
	AGUACEIROS_FORTES,
	MUITO_NUBLADO,
	NEVOEIRO,
	CEU_NUBLADO_NUVENS_ALTAS,
	NEBLINA,
	PERIODOS_CHUVA,
	CHUVA,
	PERIODOS_CHUVA_FRACA,
	CHUVA_FORTE,
	PERIODOS_CHUVA_FORTE,
	CHUVISCO,
	CHUVA_FRACA,
	NEVE,
	TROVOADA,
	GRANIZO,
	AGUACEIROS_E_TROVOADA,
	GEADA;
	
}
